### ISSUE TITLE
LogitechPresentation.download.recipe Failing to find match

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/grahampugh-recipes#10]
This recipe fails on URLSearching on unable to find a match.
A curl of the page (https://support.logitech.com/en_us/software/logi-presentation) returns a 302 message.
Visiting it in Safari redirects to https://support.logi.com/hc/en-us/articles/360025141634 which performs an OS autodetect.
I'm look into it further now and hope to be able to supply a pull request.

**Comment by grahampugh** [comment]
Solved in 66cd3a7.

**Comment by grahampugh** [comment]
Thanks @Daz-wallace and @macmule !
