### ISSUE TITLE
FR: Add support for pulling ARM versions of IntelliJ

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/grahampugh-recipes#102]
Heya,

Taking a look at your IntelliJ recipes and by default they only pull the Intel versions of IntelliJ CE, and not the Apple Silicon / ARM versions.
For example:
- The Intel path is https://download.jetbrains.com/idea/ideaIC-2022.1.2.dmg
- The ARM path is https://download.jetbrains.com/idea/ideaIC-2022.1.2-aarch64.dmg

Not sure how easy it'd be to tweak the custom IntellijURLProvider.py processor to allow this feature?
Thanks!

**Comment by grahampugh** [comment]
Hi Daz

Thanks for the investigation. I've now updated the processor so that it accepts an `arch` parameter. If you supply the `arch` value `arm64` it will return the ARM path as you describe. Any other value (inc. `intel`) will return the Intel path.
