### ISSUE TITLE
Error running Nudge-pkg-upload.jamf

### ISSUE THREAD

**Issue by jessemcbrower** [autopkg/grahampugh-recipes#108]
Looks like the parent recipes for Nudge-pkg-upload.jamf were removed. I was wondering if there were plans to re-add anything for Nudge, or if there was a better way to keep it patched. These were the recipes it couldn't find:

"Could not find parent recipe for com.github.grahampugh.recipes.pkg.Nudge
Could not find parent recipe for com.github.grahampugh.recipes.jamf.Nudge-pkg-upload"

Thanks!

**Comment by bdruth** [comment]
I'm running into the same issue - did anyone get anywhere with this?

**Comment by grahampugh** [comment]
Weird. `com.github.grahampugh.recipes.pkg.Nudge` is certainly there. Are you still having the problem?

**Comment by SeanHansell** [comment]
@jessemcbrower do you have the repo `erikng-recipes` installed as well as this one? That's where the parent recipe for this one lives.

**Comment by grahampugh** [comment]
Hey all. I think there was an old mistake in the parent recipe key of the Nudge-pkg-upload.jamf recipe. Delete your old recipe override to fix it.
