### ISSUE TITLE
Microsoft Office recipes think they're children of jss-recipes

### ISSUE THREAD

**Issue by NoahDowdDraper** [autopkg/grahampugh-recipes#110]
When run through autopkg or AutoPkgr, all of the Microsoft Office .jamf recipes state that they're children of recipes in the jss-recipes repo (including the pkg-install ones). To create overrides for them, JSSImporter needs to be installed and --ignore-deprecation is required.
Once that's present, they complain about a couple of lines of python (change "is not" to "!=") and throw an error "'Element' object has no attribute 'getchildren'".
[Autopkg.txt](https://github.com/autopkg/grahampugh-recipes/files/9872690/Autopkg.txt)

**Comment by grahampugh** [comment]
I can see why this happened. The old jss recipes were very non-standard, with a direct download recipe as parent instead of a pkg recipe, and extra processes in there to do the job that should have been in a pkg recipe. So it'll need some manual work to update to point to a still-relevant pkg recipe somewhere.

**Comment by NoahDowdDraper** [comment]
I think I got them to work by setting the parents to Rich Trouton’s pkg recipes, if that’s helpful at all.

Noah Dowd
Mac Desktop Engineer
Information Technology Services
Draper
617-258-3314<tel:6172583314>
***@***.******@***.***>

Ná bris do loirgin ar stól nach bhfuil i do shlí.

On Oct 26, 2022, at 3:21 PM, Graham Pugh ***@***.***> wrote:



I can see why this happened. The old jss recipes were very non-standard, with a direct download recipe as parent instead of a pkg recipe, and extra processes in there to do the job that should have been in a pkg recipe. So it'll need some manual work to update to point to a still-relevant pkg recipe somewhere.

**Comment by grahampugh** [comment]
Thanks for the hints, these should now be fixed.
