### ISSUE TITLE
ChoicesXMLGenerator.py Python Error in Python 3.10

### ISSUE THREAD

**Issue by lhetke** [autopkg/grahampugh-recipes#112]
The following Python script throws an error when run with AutoPkg 2.7+ and Python 3.10+

CommonProcessors/ChoicesXMLGenerator.py

This is the error message:

`WARNING: /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/CommonProcessors/ChoicesXMLGenerator.py: cannot import name 'writePlist' from 'plistlib' (/Library/AutoPkg/Python3/Python.framework/Versions/3.10/lib/python3.10/plistlib.py)`

I found out that the plistlib module in Python 3 uses dump() and load() to work with plist data, instead of writePlist() and readPlistFromString(). https://docs.python.org/3.10/library/plistlib.html

I don't know enough Python to rewrite the script myself, but I hope this information helps :)

**Comment by ehjmx** [comment]
I checked out the new ChoicesXMLGenerator and can confirm that it works. 
Thank you for updating it.
