### ISSUE TITLE
Spotify downloading as arm

### ISSUE THREAD

**Issue by itsupportzf** [autopkg/grahampugh-recipes#114]
Hi,

Our company has mixture of intel and arm based machines. The recipe download arm based file. I am using the spotify-pkg-upload.jamf via autopkgr app. attached is a screenshot

It looks like jamf mac apps pushes intel based. Is there something I can do when i make the overide of the recipe so it creates intel based pkg
<img width="648" alt="Screen Shot 2022-12-20 at 9 26 30 AM" src="https://user-images.githubusercontent.com/64274928/208694104-c041551c-a920-49f7-9631-370790771098.png">

**Comment by grahampugh** [comment]
Hi there, you would have to check the download recipe. The parent recipe of the jamf recipe is Spotify.pkg in homebysix-recipes.
