### ISSUE TITLE
PostProcessors/LastRecipeRunResult.py not logging pkg_uploaded value

### ISSUE THREAD

**Issue by onecheapgeek** [autopkg/grahampugh-recipes#118]
As a result, PrePRocessors/LastRecipeRunChecker.py always has that value set to false because it looks for that value in latest_version.json.

It looks like 
`                  "pkg_uploaded": {
            "description": ("The upload status from the run"),
            "required": False,
            "default": "",
        },
`
around line 94-ish

and 
`        data["pkg_uploaded"] = pkg_uploaded
`
around line 189-ish correct this issue

**Comment by grahampugh** [comment]
Hi, thanks for the info. I have now updated the processor with the missing `pkg_uploaded` and `pkg_metadata_uploaded` keys.

**Comment by onecheapgeek** [comment]
Thanks for the quick fix! Now patching is running smooth.
