### ISSUE TITLE
Nudge Versioner Plist Issue

### ISSUE THREAD

**Issue by SeanHansell** [autopkg/grahampugh-recipes#119]
I noticed when the last change to the Nudge recipe broke my setup.

Nudge releases contain 4 different potential PKGs. Nudge, Nudge Suite, Nudge Logger, and Nudge Launch Agent.
See: https://github.com/macadmins/nudge/releases

@erikng has the download recipe setup with an optional "TYPE" variable to download the other releases. I use the "_Suite" value for this, since it contains all 3 Nudge components.

Commit: #117 updated the version pathing for the default Nudge package.

This works fine for the default Nudge Release, but it breaks the Nudge_Suite type because it's still looking for the .app payload in the old location (./payload/Applications/Utilities/Nudge.app). This would also break with the other two payloads, Logger and LaunchAgent because those don't have the app bundle at all.

I'll try to come up with a fix, but wanted you to know where I was at.

I hate YAML. Thanks for your time.
<img width="366" alt="Screenshot 2023-03-30 at 8 20 48 AM" src="https://user-images.githubusercontent.com/9552880/228928700-bedca2b4-e7d8-437b-8550-6e4449acdf08.png">

**Comment by grahampugh** [comment]
The recipe was still working for me after clearing the cache, but I've now made a change that adds the Type to the package name and clears the `payload` and `unpack` folders after use, as their presence was causing the recipe problems to run again for some reason.

**Comment by SeanHansell** [comment]
Still not working for me for the Nudge_Suite type even with the update.

Versioner can't find the Info.plist because it's in a different path than the one the recipe is looking for.

**Comment by grahampugh** [comment]
Weird. It worked for me. Did you clear your recipe cache?

**Comment by grahampugh** [comment]
Close due to no response.
