### ISSUE TITLE
Issue with Parent recipes not pulling

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/grahampugh-recipes#121]
I am using Autopkgr and it keeps saying 

Could not find parent recipe for com.github.autopkg.grahampugh-recipes.jamf.1Password

This happens for all. Am I missing something our needs setup?
<img width="401" alt="Screenshot 2023-05-05 at 3 47 54 PM" src="https://user-images.githubusercontent.com/50874013/236555803-f268eec7-25c5-4c72-b5f0-1a273efce016.png">
<img width="648" alt="Screenshot 2023-05-05 at 3 47 57 PM" src="https://user-images.githubusercontent.com/50874013/236555824-cfef8e71-6bf8-46b9-9051-dca28ee10188.png">

**Comment by tsinghzf** [comment]
I did not realize those were dependent on a parent recipe. DO you have a list handy for the recipes you have setup for .jamf I can reference please?

**Comment by grahampugh** [comment]
Use `autopkg info <recipe-name>` to find out information about the parent repos.
