### ISSUE TITLE
DellDisplayAndPeripheralManager.download.recipe.yaml failing to find downloading Package in zip

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/grahampugh-recipes#126]
Hey Graham!
Looks like Dell have changed the zip format so that DellDisplayAndPeripheralManager.download.recipe.yaml's current location for the CodeSignatureVerifier (`"%RECIPE_CACHE_DIR%/unzip/DDPM_Installer.pkg"`) now needs to be `"%RECIPE_CACHE_DIR%/unzip/DDPMv1.1.1.0038/DDPM_Installer.pkg"`

I'll get a PR together now.

Error:
`com.github.grahampugh.recipes.download.DellDisplayAndPeripheralManager
        Error in com.github.grahampugh.recipes.download.DellDisplayAndPeripheralManager: Processor: CodeSignatureVerifier: Error: Error processing path '/Users/Darren.Wallace/Library/AutoPkg/Cache/com.github.grahampugh.recipes.download.DellDisplayAndPeripheralManager/unzip/DDPM_Installer.pkg' with glob. `

**Comment by grahampugh** [comment]
Thanks. I bet they change it back in the next version....

**Comment by Daz-wallace** [comment]
Yup, and....erm sorry I missed updating the .pkg recipe. Let me get another PR in
