### ISSUE TITLE
FileMakerProAdvancedUpdater.download.recipe MAJOR_VERSION 

### ISSUE THREAD

**Issue by eshirk** [autopkg/grahampugh-recipes#13]
Any chance that MAJOR_VERSION can be updated to 18? Alternatively, could major-version-specific download recipes be created? Use case is as a parent recipe in a munki recipe, and as yet, I don't think an override can serve as a parent recipe.

**Comment by grahampugh** [comment]
@eshirk Yes, you can override `MAJOR_VERSION`.

**Comment by eshirk** [comment]
My bad…a case typo was preventing the child Munki recipe from successfully overriding the parent download recipe. All good, so I'll close the issue. Thanks!
