### ISSUE TITLE
MendeleyReferenceManager.app CFBundleShortVersionString does not include "-x64"

### ISSUE THREAD

**Issue by katidzehnder** [autopkg/grahampugh-recipes#133]
Please adjust the recipe to exclude "-x64" from <verision> in MendeleyReferenceManager.download.recipe.yaml

**Comment by grahampugh** [comment]
Hi! I assume this is so that the `version` string doesn't contain `-x64`. I have now altered the recipe to fix that. I wonder if they plan to release an `-arm` version - so far this doesn't exist in the .yml file.
