### ISSUE TITLE
FileZilla download recipe can't find match

### ISSUE THREAD

**Issue by andreilabin** [autopkg/grahampugh-recipes#134]
URLTextSearcher finds no match at https://filezilla-project.org/download.php?show_all=1.
The present downloadlink is "https://dl3.cdn.filezilla-project.org/client/FileZilla_3.66.4_macos-x86.app.tar.bz2?h=SDTMfHlkcVWj5Ot2mvGn2w&x=1703149170"

**Comment by grahampugh** [comment]
Hi Andrei, it should be fixed now - the string changed from `macosx` to `macos`.
