### ISSUE TITLE
Jamf Compliance Editor download recipe currently failing

### ISSUE THREAD

**Issue by jelockwood** [autopkg/grahampugh-recipes#137]
@grahampugh 
As of last night your Jamf Compliance Editor download recipe has stopped working. I would presume your regex needs updating.

AutoPkgr running your recipe shows the following error.

Error in local.munki.Jamf Compliance Editor: Processor: URLTextSearcher: Error: No match found on URL: https://trusted.jamf.com/docs/establishing-compliance-baselines

I can see that the above page was updated on March 19th so the error is consistent with that date.

**Comment by grahampugh** [comment]
Hi, thanks, that will be because I believe Jamf altered the download to be a pkg instead of a zip. I'll get on it a.s.a.p.

**Comment by grahampugh** [comment]
This is now fixed.
