### ISSUE TITLE
SupportApp-Pkg.download.recipe downloads the wrong package

### ISSUE THREAD

**Issue by mathu-eth** [autopkg/grahampugh-recipes#138]
Hi Graham 

It seems like the SupportApp-Pkg.download.recipe is downloading the Support Helper instead of the Support app. I believe the regex applies to both the app and the helper, which is in the same repo.  Could you fix this? Thanks! 

Process:
  - Arguments:
      **asset_regex: .*\.pkg$**
      github_repo: root3nl/SupportApp
    Processor: GitHubReleasesInfoProvider

**Comment by grahampugh** [comment]
Hi Mathu

Thanks for the heads up. I've now fixed it, and I've created recipes for the Helper app too (I know you already have internal ones).

Cheers,
Graham
