### ISSUE TITLE
Jamf Compliance Editor download recipe issue and solution

### ISSUE THREAD

**Issue by jelockwood** [autopkg/grahampugh-recipes#142]
@grahampugh 
It looks like yesterday June 13th, that Jamf have moved the download link for their Jamf Compliance Editor tool to Github. (Hurray! 😄 )

As a result today your recipe is failing, but now and going forwards things will be much easier.

Can you indicate if you will update your recipe, otherwise I can create my own standard GitHub download recipe.

**Comment by grahampugh** [comment]
It makes sense to update the existing recipe, that's how AutoPkg is supposed to work :-) Feel free to make a PR or I'll look at it when I get a chance.
