### ISSUE TITLE
local.munki.AmazonCorrettoJava8-dataJAR: Processor: URLTextSearcher: Error: No match found

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/grahampugh-recipes#17]
Morning! Seemingly have an issue again with the Amazon Corretto Java 8 recipe not finding a valid pattern.

I'm not sure but could be a similar thing to what Rich Trouton had to tweak here - https://github.com/autopkg/rtrouton-recipes/issues/59 ?

As always, no rush or input expected for a while for the holidays, and thanks 😊

**Comment by richard-datajar** [comment]
Can confirm changing the search url to https://github.com/corretto/corretto-8/releases/latest fixes the issue.

**Comment by grahampugh** [comment]
Addressed in #19 
Thanks for the heads up.
