### ISSUE TITLE
Not picking up latest AdoptOpenJDK 11 releases

### ISSUE THREAD

**Issue by jpenney** [autopkg/grahampugh-recipes#18]
I'm not sure if this is easily addressed, but for some reason the releases for AdoptOpenJDK 11 are named incorrectly on github, so the latest build (currently `jdk11u-2020-01-09-02-59`) is not being picked up because the 2019-12-31 build (which is mis-tagged as `jdk11u-2020-12-31-15-31`) shows up higher on the page, even though it's older.

**Comment by grahampugh** [comment]
I’ve opened an issue with Adopt. I don’t intend to write a workaround for their gaffe.

**Comment by grahampugh** [comment]
Well this got fixed back in January apparently...
