### ISSUE TITLE
AdoptOpenJDK8.download.recipe fails to find valid releases

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/grahampugh-recipes#2]
Looks like the filename may have changed. 
Gonna create a PR now that looks to fix it

**Comment by Daz-wallace** [comment]
Helpful error message!

```GitHubReleasesInfoProvider
{'Input': {'asset_regex': u'^OpenJDK8U-jdk_x64_mac_hotspot_.*?.tar.gz$',
           'github_repo': u'AdoptOpenJDK/openjdk8-binaries'}}
No release assets were found that satisfy the criteria.
Failed.
Receipt written to /Users/darren/Library/AutoPkg/Cache/com.github.grahampugh.recipes.download.AdoptOpenJDK8/receipts/AdoptOpenJDK8.download-receipt-20190604-135630.plist

The following recipes failed:
    AdoptOpenJDK8.download.recipe
        Error in com.github.grahampugh.recipes.download.AdoptOpenJDK8: Processor: GitHubReleasesInfoProvider: Error: No release assets were found that satisfy the criteria.```

**Comment by grahampugh** [comment]
Hi @Daz-wallace  sorry for late response, one of those 'I'll look at that again later' messages that got lost... I figured out that the `hotspot` recipes have disappeared from the `AdoptOpenJDK/openjdk8-binaries` repo, even though the latest `hotspot` version is still downloadable directly from their website. 

My choice of the `hotspot` version was in any case arbitrary; I couldn't really figure out what the difference is. So as you suggested in your PR, I've switched the recipe to point to the `openj9` version instead, which is functioning as of today. 

I probably should check the binary versions too.

**Comment by grahampugh** [comment]
...and `OpenJDK8U-jdk_x64_mac_hotspot_8u212b04.tar.gz` seems to be there again now... `AdoptOpenJDK8.download` worked for me as is anyway.

**Comment by gobos** [comment]
Hi @grahampugh seems *hotspot*  disappear once again from https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/

**Comment by grahampugh** [comment]
@Daz-wallace reports: seems hotspot disappeared once again from https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/

**Comment by grahampugh** [comment]
Not sure why this is happening. The releases are listed on the website. Seems like a failure with the `GitHubReleasesProvider` to find the entires. Note it is also currently affecting the `AdoptOpenJDK8_Signed.download` and `AdoptOpenJDK8JRE.download` recipes.

**Comment by grahampugh** [comment]
Switched to `URLTextProvider` as `GitHubReleasesProvider` was relying on an incomplete list of items from the GitHub Releases API.
