### ISSUE TITLE
FilemakerProAdvancedUpdateURLProcessor.py is failing

### ISSUE THREAD

**Issue by eshirk** [autopkg/grahampugh-recipes#22]
Began seeing this error with the Filemaker recipes; no additional info available when run with verbosity.

WARNING: /Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/FileMaker/FilemakerProAdvancedUpdateURLProcessor.py: No module named future
Failed.

**Comment by grahampugh** [comment]
Yeah, I've been trying to update the processors for AutoPkg 2.0, but looks like it broke compatibility for older AutoPkg. I'll see what I can do.

**Comment by grahampugh** [comment]
OK, I referred to the original (https://github.com/autopkg/nzmacgeek-recipes/blob/master/FileMaker/FilemakerUpdateURLProcessor.py) which was updated recently, and merged in the changes. Perhaps it will work now.

**Comment by eshirk** [comment]
And it does work now! Thank you *very* much.

**Comment by grahampugh** [comment]
Great, no problem!
