### ISSUE TITLE
FilemakerProAdvancedUpdateURLProcessor Error

### ISSUE THREAD

**Issue by eshirk** [autopkg/grahampugh-recipes#25]
Anybody else seeing the folllowing?

Error in local.munki.FileMakerProAdvancedUpdater: Processor: FilemakerProAdvancedUpdateURLProcessor: Error: Expecting value: line 1 column 1 (char 0)

Dumping local cache had no effect.

**Comment by dcoobs** [comment]
I think this should be fixed with #28

**Comment by grahampugh** [comment]
Merged.
