### ISSUE TITLE
AdoptOpenJDK Version

### ISSUE THREAD

**Issue by eshirk** [autopkg/grahampugh-recipes#32]
For v8 at least, AdoptOpenJDK is packaging the latest release with a version number of 1.0.

**Comment by grahampugh** [comment]
Which recipe are you using? This isn't happening for me, but there are various recipes here, not all of which I use.

**Comment by eshirk** [comment]
It's AdoptOpenJDK8_Signed.munki.recipe. Looks like the problem isn't with the recipe but with the original pkg itself. I grabbed it from https://adoptopenjdk.net/releases.html and cracked it open, and there's the culprit: CFBundleShortVersionString of 1.0, though the CFBundleVersion is correct. Feel free to file this under 'never mind'.

**Comment by grahampugh** [comment]
Heh, that's why I don't use their package as the versioning was always wrong. I package it up myself in the pkg recipe.

**Comment by eshirk** [comment]
Makes sense...I don't suppose you'd be willing to whip up a munki recipe based on your pkg recipe...?😬

**Comment by grahampugh** [comment]
I'm reluctant to add Munki recipes because I cannot test them. In hindsight I should not have accepted the PR that included the Munki recipes.

**Comment by grahampugh** [comment]
@eshirk this Issue is obsoleted by the change from AdoptOpenJDK to Eclipse Temurin. I've created new recipes for this, but I do not provide Munki recipes. The signed package recipes for Temurin now extract the correct version.

**Comment by eshirk** [comment]
@grahampugh No worries about the lack of a Munki recipe; we can work around that. Thanks!
