### ISSUE TITLE
JamfUploader processors fail when HTTP2 is used

### ISSUE THREAD

**Issue by jwrn3** [autopkg/grahampugh-recipes#46]
Tested on Jamf Cloud 10.27.0-t1612450030

To extract the status code attribute from a curl call the output is parsed for a line that matches HTTP/1.1:

if "HTTP/1.1" in header and "Continue" not in header:
    r.status_code = int(header.split()[1])

However on Jamf Cloud HTTP2 is used which means the output parsing fails and then the processor fails. This issue affects 

- JamfCategoryUploader.py
- JamfComputerGroupUploader.py
- JamfExtensionAttributeUploader.py
- JamfPackageUploader.py
- JamfPolicyDeleter.py
- JamfPolicyUploader.py
- JamfScriptUploader.py

Can create PR if useful.

**Comment by grahampugh** [comment]
This has been incorporated into the recent changes of these files.
