### ISSUE TITLE
JamfPackageUploader - Metadata set and summary produced even it package is not uploaded...

### ISSUE THREAD

**Issue by everetteallen** [autopkg/grahampugh-recipes#52]
This was making me crazy, I was getting metadata update attempts and a summary  after every run of autopkg with JamfPackageUploader even if the package existed and was not uploaded.  Double check me but I think line line 670 in JamfPackageUploader.py should be 

self.pkg_uploaded = False

The current codes says:
---
else:
                self.output(
                    (
                        f"Not replacing existing {self.pkg_name} as 'replace_pkg' is set to "
                        f"{self.replace}. Use replace_pkg='True' to enforce."
                    ),
                    verbose_level=1,
                )
                self.pkg_uploaded = True

---
But maybe I am misreading it?
Anyway when I changed to False in my local copy worked as I expected...

**Comment by grahampugh** [comment]
Hi @everetteallen thanks for spotting the logic fail! I've now pushed the change you suggested. Let me know if it is still causing a problem.
