### ISSUE TITLE
AdoptOpenJDK8 download failing to find matches

### ISSUE THREAD

**Issue by jelockwood** [autopkg/grahampugh-recipes#6]
I am currently getting messages saying that AutoPkg is failing to find download matches using your recipe as below.

> Error in local.munki.AdoptOpenJDK8_Signed: Processor: GitHubReleasesInfoProvider: Error: No release assets were found that satisfy the criteria.

On examine your recipe and the repo I get the impression (possibly wrongly admittedly) that your regex is looking for a multiline match and this may be throwing it off.

> Your regex = ^OpenJDK8U-jdk_x64_mac_hotspot_.*?.pkg$
> Suggested solution = OpenJDK8U-jdk_x64_mac_hotspot_.*?.pkg

Testing yours and mine with a regex tester against the source of the repo webpage seems to suggest mine might work better.

**Comment by dcoobs** [comment]
I think it may also have to do with the fact that they're releasing openj9 and hotspot using the same [releases page](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases)

**Comment by jelockwood** [comment]
Maybe but the regex specifically looks for an OpenJDK8 and my testing suggests it is not getting any matches due to the regex.

**Comment by dcoobs** [comment]
Our autopkg seems to be happier with the addition of new [releases](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases).

**Comment by jelockwood** [comment]
Yes it came through for me. Fingers crossed for the future.

**Comment by grahampugh** [comment]
It looks like they pulled the hotspot versions of the last release. I had to change the default recipe to OpenJ9 in the meantime. Looks like it's OK now.
