### ISSUE TITLE
FilemakerProAdvancedUpdateURLProcessor update_feed request

### ISSUE THREAD

**Issue by eshirk** [autopkg/grahampugh-recipes#7]
Would it be possible to change the UPDATE_FEED from: http://www.filemaker.com/support/updaters/updater_json.txt?id=1231231231
to:
https://www.filemaker.com/support/updaters/product-updaters.txt

The former hasn't been updated with the current FMPA 18.0.2 updater, while the latter has been.

Many thanks--

**Comment by grahampugh** [comment]
Hi @eshirk - nice find. I've made the update, let me know if it succeeds.

**Comment by eshirk** [comment]
Worked a dream—thank you!

On Aug 8, 2019, at 2:58 PM, Graham R Pugh <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @eshirk<https://github.com/eshirk> - nice find. I've made the update, let me know if it succeeds.

**Comment by grahampugh** [comment]
Great!
