### ISSUE TITLE
TeX Live Utility download recipe needs change for dmg->zip change in source

### ISSUE THREAD

**Issue by eithor** [autopkg/grahampugh-recipes#78]
TeX/TeXLiveUtility.download.recipe.yaml fails due to source in github changing from .dmg asset to .zip.

Please update recipe to include Unarchiver step and change of path. It might be that the .pkg.recipe needs change also.

**Comment by grahampugh** [comment]
PR welcome, as I no longer use this recipe.

**Comment by eithor** [comment]
I'm sorry, my PR-creating-skill is non-existent. I've moved to using my own local copy which is not in GitHub. You can close the issue if you like, or I could provide you a diff.

**Comment by grahampugh** [comment]
Sure, just paste the code in here if you like and I'll make the changes.

**Comment by eithor** [comment]
[TeXLiveUtility.download.recipe.yaml.gz](https://github.com/autopkg/grahampugh-recipes/files/12497860/TeXLiveUtility.download.recipe.yaml.gz)
[TeXLiveUtility.pkg.recipe.yaml.gz](https://github.com/autopkg/grahampugh-recipes/files/12497861/TeXLiveUtility.pkg.recipe.yaml.gz)

Attached the full recipes that works, gzip so that GitHub is happy. The change to SparkleUpdateInfoProvider might not be necessary, I think it was due to my copy-paste-from a RecipeRobot example.

**Comment by grahampugh** [comment]
Hi, sorry for the delay, this is now fixed.
