### ISSUE TITLE
Unknown processor 'com.github.grahampugh.recipes.CommonProcessors/StringReplacer'

### ISSUE THREAD

**Issue by opus-nbo** [autopkg/grahampugh-recipes#93]
What did I do wrong? 

```
<key>Processor</key>
<string>com.github.grahampugh.recipes.CommonProcessors/StringReplacer</string>
```

The Processors python files should each have a folder, I guess.

**Comment by grahampugh** [comment]
Try
```
<key>Processor</key>
<string>com.github.grahampugh.recipes.commonprocessors/StringReplacer</string>
```

**Comment by opus-nbo** [comment]
I did, same result in lowercase.

**Comment by grahampugh** [comment]
Maybe you have a problem I cannot see then. Can you post your entire recipe and the `autopkg run -vvv` output?

**Comment by opus-nbo** [comment]
Look at the commented out part:

https://github.com/opus-marketing/autopkg-recipes/blob/91dd36aaf1913f4e14b38e4540f5542f8ded16f4/MAMP/MAMP.download.recipe#L54

I tried to change the value in %filename% (remove the '-Intel-x86' from the URL. Apart from the unknown processor error, I don' know if this would work. I am a beginner in writing recipes.

**Comment by grahampugh** [comment]
```            <dict>
                <key>Processor</key>
                <string>com.github.grahampugh.recipes.commonprocessors/StringReplacer</string>
                <key>Arguments</key>
                <dict>
                    <key>input_string</key>
                    <string>%filename%</string>
                    <key>string_to_replace</key>
                    <string>-Intel-x86</string>
                    <key>replacement_string</key>
                    <string></string>
                    <key>output_string</key>
                    <string>%filename%</string>
                </dict>
            </dict>
```
This worked for me.

There are other problems with your recipe, but the path to my processor is not one of them if you use lower case letters in the identifier.
