### ISSUE TITLE
FileZilla app_path invalid when downloading tar.bz2

### ISSUE THREAD

**Issue by cgolebio** [autopkg/grahampugh-recipes#97]
Currently, the app_path is:

app_path: "%RECIPE_CACHE_DIR%/downloads/%NAME%/*.app"

Since the download is a tar.bz2 file, this should actually be:

app_path: "%RECIPE_CACHE_DIR%/unzip/%NAME%.app"

**Comment by grahampugh** [comment]
Now fixed.
