### ISSUE TITLE
Feature Request: Add "insecure" flag for the curl calls in JAMF Upload

### ISSUE THREAD

**Issue by WardsParadox** [autopkg/grahampugh-recipes#98]
Some JAMF setups have the servers behind Load Balancers. These terminate SSL at the LB. The individual hosts run self signed certs. Adding these to the system keychain still throws errors with CURL (error 60). If the cert is not trusted, CURL throws an error (28) and stops.

**Comment by grahampugh** [comment]
Hi Zack, please can you submit the PR to the grahampugh/jamf-upload repo? I have my test scripts in there, so I always do my tests in there and then clone the processors into the autopkg/grahampugh-recipes repo once the tests are complete.

**Comment by WardsParadox** [comment]
Will do! I'll likely get to that on Monday

**Comment by WardsParadox** [comment]
@grahampugh Updated per request

**Comment by grahampugh** [comment]
Was resolved with https://github.com/autopkg/grahampugh-recipes/pull/99
